add_newline = false
command_timeout = 1000

[character]
success_symbol = "âœ"
error_symbol = "âœ—"
vicmd_symbol = "â®"

[git_branch]
symbol = "ï˜ "
truncation_length = 48
style = "bold purple"

[git_status]
disabled = false
style = "bright-yellow"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold cyan"

[hostname]
ssh_only = true
style = "bold green"

[username]
show_always = false
style = "bold yellow"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M:%S"
style = "bold white"

[cmd_duration]
min_time = 500
show_milliseconds = true
style = "bold red"

[memory_usage]
disabled = true
threshold = 70
symbol = "ï¡š "
style = "bold dimmed blue"

[battery]
disabled = true
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ”Œ"
empty_symbol = "ğŸª«"
style = "bold yellow"

[jobs]
symbol = "âœ¦ "
number_threshold = 1
style = "bold magenta"

[package]
disabled = true
symbol = "ğŸ“¦ "
style = "bold green"

[os]
disabled = true
style = "bold blue"

[line_break]
disabled = false

